# notification-queue/Dockerfile

FROM maven:3.9.6-eclipse-temurin-21-alpine AS build
WORKDIR /app
COPY . .
RUN mvn clean package -DskipTests

FROM eclipse-temurin:21-jdk-alpine
WORKDIR /app
COPY --from=build /app/target/notification-queue-0.0.1-SNAPSHOT.jar app.jar
CMD ["java", "-jar", "app.jar"]
